CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_ZMK_KSCAN_GPIO_DRIVER=y

# CONFIG_ZMK_KSCAN_MATRIX_INTERRUPTS=n
CONFIG_GPIO_PCA95XX_INTERRUPT=n
CONFIG_ZMK_KSCAN_MATRIX_POLLING=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
